[commands] fix generator for latest python-openstackclient
* suppress deprecation warning messages

UserWarning: Module novaclient.v1_1 is deprecated (taken as a basis for
novaclient.v2). The preferable way to get client class or object you can
find in novaclient.client module.
  warnings.warn("Module novaclient.v1_1 is deprecated (taken as a basis
for "

* use --os-auth-type token to make the openstack help command workable

ERROR: openstack Authentication type must be selected with
--os-auth-type

* add new commands

Change-Id: I14c9479ef7ded7b7c62b0d976706e3d7e26a6cd6